### ISSUE TITLE
Checker crashing on running certain pieces of code

### ISSUE THREAD

**Issue by Wesss** [gyhughes/checker-framework#13]
Upon trying to run the checker on a specific piece of code, a NullPointerException is thrown, crashing the program.

I can't attach java files here directly, so I put a folder on drive with the files needed to reproduce the error.
https://drive.google.com/drive/folders/0ByNy04xRyVnXLU9jUllzYVlFd00
Edit: moved to drive

Stack trace:

[coxw2@detroit zxing-gridsampler]$ javac -processor IndexChecker -AprintErrorStack BitMatrix.java 
error: SourceChecker.typeProcess: unexpected Throwable (NullPointerException) while processing BitMatrix.java
  Compilation unit: BitMatrix.java
  Exception: java.lang.NullPointerException; Stack trace: org.checkerframework.checker.index.IndexStore.applyTransfer(IndexStore.java:66)
  org.checkerframework.checker.index.IndexStore.updateForMethodCall(IndexStore.java:42)
  org.checkerframework.checker.index.IndexStore.updateForMethodCall(IndexStore.java:19)
  org.checkerframework.framework.flow.CFAbstractTransfer.visitMethodInvocation(CFAbstractTransfer.java:892)
  org.checkerframework.framework.flow.CFAbstractTransfer.visitMethodInvocation(CFAbstractTransfer.java:101)
  org.checkerframework.dataflow.cfg.node.MethodInvocationNode.accept(MethodInvocationNode.java:81)
  org.checkerframework.dataflow.analysis.Analysis.callTransferFunction(Analysis.java:362)
  org.checkerframework.dataflow.analysis.Analysis.performAnalysis(Analysis.java:220)
  org.checkerframework.framework.type.GenericAnnotatedTypeFactory.analyze(GenericAnnotatedTypeFactory.java:893)
  org.checkerframework.framework.type.GenericAnnotatedTypeFactory.analyze(GenericAnnotatedTypeFactory.java:861)
  org.checkerframework.framework.type.GenericAnnotatedTypeFactory.performFlowAnalysis(GenericAnnotatedTypeFactory.java:805)
  org.checkerframework.framework.type.GenericAnnotatedTypeFactory.checkAndPerformFlowAnalysis(GenericAnnotatedTypeFactory.java:1090)
  org.checkerframework.framework.type.GenericAnnotatedTypeFactory.annotateImplicit(GenericAnnotatedTypeFactory.java:1057)
  org.checkerframework.framework.type.GenericAnnotatedTypeFactory.annotateImplicit(GenericAnnotatedTypeFactory.java:1037)
  org.checkerframework.framework.type.AnnotatedTypeFactory.getAnnotatedType(AnnotatedTypeFactory.java:921)
  org.checkerframework.framework.type.AnnotatedTypeFactory.getAnnotatedType(AnnotatedTypeFactory.java:2082)
  org.checkerframework.common.basetype.BaseTypeVisitor.visitClass(BaseTypeVisitor.java:297)
  org.checkerframework.common.basetype.BaseTypeVisitor.visitClass(BaseTypeVisitor.java:171)
  com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:720)
  com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:50)
  org.checkerframework.framework.source.SourceVisitor.visit(SourceVisitor.java:70)
  org.checkerframework.framework.source.SourceChecker.typeProcess(SourceChecker.java:943)
  org.checkerframework.common.basetype.BaseTypeChecker.typeProcess(BaseTypeChecker.java:448)
  org.checkerframework.javacutil.AbstractTypeProcessor$AttributionTaskListener.finished(AbstractTypeProcessor.java:209)
  com.sun.tools.javac.api.ClientCodeWrapper$WrappedTaskListener.finished(ClientCodeWrapper.java:681)
  com.sun.tools.javac.api.MultiTaskListener.finished(MultiTaskListener.java:111)
  com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1342)
  com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1296)
  com.sun.tools.javac.main.JavaCompiler.compile2(JavaCompiler.java:901)
  com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:860)
  com.sun.tools.javac.main.Main.compile(Main.java:523)
  com.sun.tools.javac.main.Main.compile(Main.java:381)
  com.sun.tools.javac.main.Main.compile(Main.java:370)
  com.sun.tools.javac.main.Main.compile(Main.java:361)
  com.sun.tools.javac.Main.compile(Main.java:56)
  com.sun.tools.javac.Main.main(Main.java:42)
1 error

**Comment by jsantino** [comment]
while i can reproduce this with the release(as you did) i do not get this behaviour using eclipse or while building form source. as such i can not address this issue at this time, since i can not make releases to test. If this error persists in future release we may decide to look at it then. possibly making intermittent test "releases" to see if our fixes address this bug.

**Comment by Wesss** [comment]
I resolved all of my PATH/building problems, built the most recent checker, and then more carefully created a new user distribution. I can no longer recreate this problem.
