### ISSUE TITLE
More informative message when index is a manifest literal

### ISSUE THREAD

**Issue by mernst** [gyhughes/checker-framework#18]
When the index argument is a literal, one can receive an error message like this:

```
src/plume/TestPlume.java:1392: warning: [array.access.unsafe.high] Potentially unsafe array access: the index could be too high
        int goal_r = rm[0];
                        ^
  found   : @NonNegative int
  required: @IndexFor("rm") int
```

It would be good to create a different error key than `array.access.unsafe.high`, whose message gives the type of the array (the needed type will be `@MinLen(...)` rather than than of the constant index expression.

**Comment by jsantino** [comment]
Message for literals changed to:
Potentially unsafe array access: index could be too high
        int m = arr[5];
  array is :@Unknown int @MinLen(2) []
  index found   : 5
  index required: literal less than 2
