### ISSUE TITLE
@IndexFor() should require an argument

### ISSUE THREAD

**Issue by mernst** [gyhughes/checker-framework#23]
It is meaningless to write these annotations

```
@IndexFor()
@IndexOrHigh()
@IndexOrLow()
@LTLength()
@MinLen()
```

because an argument should always be required.  However, the Index Checker permits this and many of the Index Checker's tests use it.

The default arguments should be removed from the definitions of these qualifiers.  That will force you to change all tests so that they pass an array name whenever using these qualifiers.

**Comment by jsantino** [comment]
Done
